name: Test
on:
  push: {}
  pull_request:
    types: [opened, synchronize]

jobs:
  integration:
    runs-on: ubuntu-latest
    # don't run integration tests on push unless it's the main branch
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: npm test
  createComment:
    runs-on: ubuntu-latest
    # only run on push events
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: node test/fixtures/app.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
