on:
  [push, pull_request]

name: Test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Debug
      run: echo '${{ toJson(github) }}'
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm run lint  
    - run: npm test